cosmo:
  tickets:
    serverSecret: 73d320ab-e7d3-4183-9a62-9628e5efe181
    serverInteger: 163184592
  caldav:
    schedulingEnabled: true
  event:
    validation:
      allowed:
        recurrence:
          frequencies: DAILY,WEEKLY,MONTHLY,YEARLY,SECONDLY
      summary:
        min:
          length: 0
        max:
          length: 2137483647
      location:
        min:
          length: 0
        max:
          length: 2137483647
      description:
        min:
          length: 0
        max:
          length: 2137483647
      attendees:
        max:
          length: 100
      icaldata:
        #1 MB in bytes
        max:
          length: 1048576
  user:
    password:
      min:
        length: 5
      max:
        length: 25

# Connection timeout for reaching external content when validation is performed (in millis)
external:
  content:
    connection:
      timeout: 10000
    size: 1048576
    non:
      proxyed:
        hosts:
calendar:
  server:
    productId: COSMO

server:
  port: 8080
  servlet:
    context-path: /cosmo
spring:
  application:
    name: cosmo-webapp
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:33060/test?autoReconnect=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: create
      hibernate.id.new_generator_mappings: false

mariaDB4j:
  port: 33060

ldap:
  port: 8442
  host: ldap://127.0.0.1
  parameters: ou=caldav,ou=services,dc=me,dc=local