cosmo:
  tickets:
    serverSecret: 73d320ab-e7d3-4183-9a62-9628e5efe181
    serverInteger: 163184592
  caldav:
    schedulingEnabled: true
  event:
    validation:
      allowed:
        recurrence:
          frequencies: DAILY,WEEKLY,MONTHLY,YEARLY,SECONDLY
      summary:
        min:
          length: 0
        max:
          length: 2137483647
      location:
        min:
          length: 0
        max:
          length: 2137483647
      description:
        min:
          length: 0
        max:
          length: 2137483647
      attendees:
        max:
          length: 100
      icaldata:
        #1 MB in bytes
        max:
          length: 1048576
  user:
    password:
      min:
        length: 5
      max:
        length: 25

# Connection timeout for reaching external content when validation is performed (in millis)
external:
  content:
    connection:
      timeout: 10000
    size: 1048576
    non:
      proxyed:
        hosts:
    user-agent: MyApplication/1.0
calendar:
  server:
    productId: COSMO

server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: webapp
  datasource:
    url: jdbc:mysql://localhost:3306/cosmodb?autoReconnect=true
    username: root
    password: aaabbb
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  ldap:
    urls: ldap://127.0.0.1
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: validate
      hibernate.id.new_generator_mappings: false
  security:
    enable-csrf: true
    enable-cors: true

mariaDB4j:
  port: 3306

ldap:
  urls: ldap://127.0.0.1:8442
  manager:
    username: cn=calendar,ou=hosts,dc=me,dc=local
    password:
  auth:
    base: ou=accounts,ou=caldav,ou=services,dc=me,dc=local
    user:
      pattern: uid={0}
  email:
    filter: (&(sendmailMTAMapValue=%u)(o=%o))
    base: ou=other,ou=services,dc=me,dc=local
    search-scope: SUBTREE
    attribute: sendmailMTAKey

management:
  endpoints:
    web:
      base-path: /url
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: always

logging:
  level:
    org:
      springframework:
#        security: DEBUG
#        ldap: DEBUG

